---
name: WWW-Search-PharmGKB
version: 1.08
author:
  - Arun Venkataraman <arvktr@gmail.com>
abstract: Search and retrieve information from the PharmGKB database
license: perl
requires:
  SOAP::Lite: 0
  English: 0
build_requires:
  Test::More: 0
provides:
  WWW::Search::PharmGKB:
    file: lib/WWW/Search/PharmGKB.pm
    version: 1.08
